version: 2.1

executors:
  nodejs-executor:
    docker:
      - image: node:16
    working_directory: ~/repo

jobs:
  run-lints:
    executor: nodejs-executor
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            apt-get update && apt-get install -y make
      - run:
          name: Run Linting
          command: make lint
  run-tests:
    executor: nodejs-executor
    steps:
      - checkout
      - run:
         name: Run testing
         command: make run


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - run-lints
      - run-tests:
         requires:
           - run-lints
