version: 2.1

executors:
  nodejs-executor:
    docker:
      - image: cimg/node:18
    working_directory: ~/repo

jobs:
  run-lints:
    executor: nodejs-executor
    steps:
      - checkout
      - run:
          name: Install Make
          command: |
            sudo apt-get update && sudo apt-get install -y make
      - run:
          name: Run Linting
          command: make lint

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - run-lints
